port: 3300

database:
  pool: 10
  adapter: mysql2
  database: casserver
  username: devUser
  password: devAdmin
  host: db
  reconnect: true

authenticator:
  class: CASServer::Authenticators::SQLEncrypted
  database:
    adapter: mysql2
    database: xorro_accounts_development
    username: devUser
    password: devAdmin
    host: db
    reconnect: true
  user_table: users
  username_column: username
  encrypt_function:  'user.encrypted_password == Digest::SHA256.hexdigest("#{user.encryption_salt}::#{@password}")'
  extra_attributes: id, f_name, l_name, email, institutions, updated_at

theme: xorro

organization: Xorro

infoline: Powered by <a href="http://code.google.com/p/rubycas-server/">RubyCAS-Server</a>

default_locale: en
